schedule:
  logo: "assets/title.png"
  start: 9
  end: 24

events:
  Sunday:
    9:
      name:        Residence Move-In
      color:       blue
      end:         11

    12:
      name: Seminar
      color: green
      end: 16

    16:
      name:        Residence Orientation
      color:       red
      end:         20

  Monday:
    9:
      name:        Commuter Registration
      color:       blue
      end:         10.5

    10.5:
      name:        Meet Your Dons
      color:       orange
      end:         12

    12:
      name:        Grand Meet & Greet
      color:       green
      end:         14

    14:
      name:        Opening Ceremonies
      color:       red
      end:         15.5

    15.5:
      name:        Frosh dance
      color:       green
      end:         16.5

    16.5:
      name:        Scavenger Hunt
      color:       yellow
      end:         17.5

    18:
      name:        Dinner with the Dean
      color:       purple 
      end:         19.5

    19.5:
      name:        Dissolve
      color:       blue
      end:         21

    21:
      name:        Bright Lights
      color:       black
      end:         24

  Tuesday:
    9:
      name: empty 
      color: black
      end: 24

  Wednesday:
    9:
      name: empty
      color: black
      end: 24

  Thursday:
    9:
      name: empty
      color: black
      end: 24

  Friday:
    9:
      name: empty
      color: black
      end: 24
